using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using CraftingApp.Models;

using Xamarin.Forms;

[assembly: Dependency(typeof(CraftingApp.Services.MockDataStore))]
namespace CraftingApp.Services
{
    public class MockDataStore : IDataStore<Item>
    {
        bool isInitialized;
        List<Item> items;

        public async Task<bool> AddItemAsync(Item item)
        {
            await InitializeAsync();

            items.Add(item);

            return await Task.FromResult(true);
        }

        public async Task<bool> UpdateItemAsync(Item item)
        {
            await InitializeAsync();

            var _item = items.Where((Item arg) => arg.Id == item.Id).FirstOrDefault();
            items.Remove(_item);
            items.Add(item);

            return await Task.FromResult(true);
        }

        public async Task<bool> DeleteItemAsync(Item item)
        {
            await InitializeAsync();

            var _item = items.Where((Item arg) => arg.Id == item.Id).FirstOrDefault();
            items.Remove(_item);

            return await Task.FromResult(true);
        }

        public async Task<Item> GetItemAsync(string id)
        {
            await InitializeAsync();

            return await Task.FromResult(items.FirstOrDefault(s => s.Id == id));
        }

        public async Task<IEnumerable<Item>> GetItemsAsync(bool forceRefresh = false, string category = null)
        {
            await InitializeAsync();

            return await Task.FromResult(items.FindAll(item => item.Category == category));
        }

        public Task<bool> PullLatestAsync()
        {
            return Task.FromResult(true);
        }


        public Task<bool> SyncAsync()
        {
            return Task.FromResult(true);
        }

        public async Task InitializeAsync()
        {
            if (isInitialized)
                return;

            await Task.Run(() =>
            {
                // https://api.albiononlinedatabase.com/img/items/backgrounds/T5_background.png
                // https://api.albiononlinedatabase.com/img/items/icons/METALBAR.png
                // https://api.albiononlinedatabase.com/img/items/icons/ORE.png
                // https://api.albiononlinedatabase.com/img/items/backgrounds/item_background.png

                items = new List<Item>();
                var _items = new List<Item>
                {
                    // wood
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Birch Logs", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Weight="1.5", DestinyBoard="1", Production="1", Description="Birch Logs are a resource which can be acquired by using an Axe to chop down Birch trees. Birch Logs are a tier 2 resource. Can be refined into Birch Planks at a Lumbermill."},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Chestnut Logs", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/6/6a/Chestnut_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/0/01/Chestnust.jpg", Tier="3", Weight="1.5", DestinyBoard="1", Production="1", Description="Chestnut Logs are a resource which can be acquired by using an Axe to chop down Chestnut trees. Birch Logs are a tier 3 resource. Can be refined into Chestnut Planks at a Lumbermill."},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Pine Logs", Icon = "https://vignette3.wikia.nocookie.net/albiononline/images/5/57/Pine_Logs.png", Image="http://albionresource.weebly.com/uploads/8/5/9/9/85991866/t4pine-log_orig.png", Tier="4", Weight="1.5", DestinyBoard="1", Production="1", Description="Pine Logs are a resource which can be acquired by using an Axe to chop down Pine trees. Pine Logs are a tier 4 resource. Can be refined into Pine Planks at a Lumbermill."},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Cedar Logs", Icon = "https://vignette3.wikia.nocookie.net/albiononline/images/6/63/Cedar_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Weight="1.5", DestinyBoard="1", Production="1", Description="Cedar Logs are a resource which can be acquired by using an Axe to chop down Cedar trees. Cedar Logs are a tier 5 resource. Can be refined into Cedar Planks at a Lumbermill."},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Bloodoak Logs", Icon = "https://vignette3.wikia.nocookie.net/albiononline/images/1/11/Bloodoak_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Weight="1.5", DestinyBoard="1", Production="1", Description="Bloodoak Logs are a resource which can be acquired by using an Axe to chop down Bloodoak trees. Bloodoak Logs are a tier 6 resource. Can be refined into Bloodoak Planks at a Lumbermill."},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Ashenbark Logs", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/5/50/Ashenbark_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Weight="1.5", DestinyBoard="1", Production="1", Description="Ashenbar Logs are a resource which can be acquired by using an Axe to chop down Ashenbar trees. Ashenbar Logs are a tier 7 resource. Can be refined into Ashenbar Planks at a Lumbermill."},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Wood", Text = "Whitewood Logs", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/5/58/Whitewood_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Weight="1.5", DestinyBoard="1", Production="1", Description="WhiteOak Logs are a resource which can be acquired by using an Axe to chop down WhiteOak trees. WhiteOak Logs are a tier 8 resource. Can be refined into WhiteOak Planks at a Lumbermill."},

                    // planks
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Birch Planks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/8/85/Birch_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Materials=new string[1]{"Wood"}, Weight="0.8", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Chestnut Planks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/c/cf/Chestnut_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[1]{"Wood"}, Weight="1.1", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Pine Planks", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/e/e4/Pine_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Cedar Planks", Icon = "https://vignette3.wikia.nocookie.net/albiononline/images/2/2d/Cedar_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Bloodoak Planks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/a/ad/Bloodoak_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Ashenbark Planks", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/b/b2/Ashenbark_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Planks", Text = "Whitewood Planks", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/5/58/Whitewood_Planks.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // metal
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Copper Ore", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/7/78/Copper_Ore.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Tin Ore", Icon = "https://vignette1.wikia.nocookie.net/albiononline/images/c/c4/Tin_Ore.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Iron Ore", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/8/87/Iron_Ore.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Weight="3.4", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Titanium Ore", Icon = "https://vignette4.wikia.nocookie.net/albiononline/images/3/34/Titanium_Ore.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Runite Ore", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/0/02/Runite_Ore.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Meteoite Ore", Icon = "https://vignette1.wikia.nocookie.net/albiononline/images/7/72/Mythical_Meteorite_Ore.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Metal", Text = "Adamantium Ore", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // bars
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Copper Bars", Tier="2", Icon = "https://vignette1.wikia.nocookie.net/albiononline/images/f/f1/Copper_Bar.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Materials=new string[1]{"Metal"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Bronze Bars", Tier="3", Icon = "https://vignette3.wikia.nocookie.net/albiononline/images/4/4c/Bronze_Bar.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Materials=new string[1]{"Metal"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Steel Bars", Tier="4", Icon = "https://vignette3.wikia.nocookie.net/albiononline/images/2/20/Steel_Bar.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Materials=new string[1]{"Metal"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Titanium Steel Bars", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{"Metal"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Runite Steel Bars", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[1]{"Metal"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Meteoite Steel Bars", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Materials=new string[1]{"Metal" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bars", Text = "Adamantium Steel Bars", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Materials=new string[1]{"Metal" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // fibers
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Cotton", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Flax", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Hemp", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Skyflower", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Redleaf Cotton", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Sunflax", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Fibers", Text = "Ghost Hemp", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // cloth
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Simple Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Neat Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Fine Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Ornate Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Lavish Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Opulent Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Cloth", Text = "Baroque Cloth", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Materials=new string[1]{"Fiber"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // hide
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "Snake hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "Large Frog hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "Lizard hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "Large Snake hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "DireSnake hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "DireFrog hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hides", Text = "DireLizard hide", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // leather
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Stiff Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Thick Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Worked Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Cured Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Hardened Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Reinforced Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Leathers", Text = "Fortified Leather", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Materials=new string[1]{"Wood"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // stone
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Limestone", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Sandstone", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Travertine", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Granite", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Slate", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Basalt", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Stones", Text = "Marble", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // blocks
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Limestone Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Sandstone Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Travertine Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Granite Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Slate Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Basalt Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="7", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Blocks", Text = "Marble Blocks", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="8", Materials=new string[1]{"Stone"}, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // professions
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Toolmaker", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Turnip Salad", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Warrior Forge", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Mutton Stew", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Mage Tower", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Mutton Sandwich", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Butcher", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Cabbage Soup", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Smelter", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Wheat Soup", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Alchemist", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Pork Omelette", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Saddler", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Goat Stew", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Lumbermill", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Carrot Soup", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Cook", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Goose Pie", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Hunter Lodge", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Potato Salad", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Tanner", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Chicken Pie", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Professions", Text = "Weaver", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", FavoriteFood="Chicken Omelette", Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // crops
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Carrots", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="1", Materials=new string[1]{ "Seed" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Beans", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Materials=new string[1]{ "Seed" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Wheat", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[1]{ "Seed" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Chicken", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Hen Eggs", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Turnip", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[1]{ "Seed" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Goat", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Goat Butter", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Goat Milk", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Cabbage", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{ "Seed" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Goose", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Goose Eggs", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Potato", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[1]{ "Seed" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Mutton", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Crops", Text = "Sheep Butter", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[2]{ "Animal", "Crop" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // foods
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Carrot Soup", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="1", Materials=new string[1]{"Carrots" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Bean Salad ", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="2", Materials=new string[2]{ "Carrots", "Beans" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Wheat Soup", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[1]{"Wheat" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Chicken Omelette", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[3]{ "Wheat", "Raw Chicken", "Hen Eggs" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Chicken Pie", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="3", Materials=new string[2]{"Wheat", "Raw Chicken" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Turnip Salad", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[2]{ "Wheat", "Turnip" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Goat Stew", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[3]{ "Wheat", "Turnip", "Raw Goat" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Goat Sandwitch", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[3]{"Wheat", "Raw Goat", "Goat Butter" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Bread", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="4", Materials=new string[1]{"Wheat" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Cabbage Soup", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[1]{"Cabbage" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Goose Omelette", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[3]{ "Cabbage", "Raw Goose", "Goose Eggs" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Goose Pie", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="5", Materials=new string[4]{"Wheat", "Goat Milk", "Cabbage", "Raw Goose" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Potato Salad", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[2]{ "Cabbage", "Potato" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Mutton Stew", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[3]{ "Wheat", "Potato", "Raw Mutton" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Foods", Text = "Mutton Sandwich", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tier="6", Materials=new string[3]{ "Wheat", "Raw Mutton", "Sheep Butter" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    // hunter weapons
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Bow", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[7]{"2","3","4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Spear", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[6]{"3","4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Dagger", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[6]{"3","4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Quarterstaff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[6]{"3","4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Nature Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[6]{"3","4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Torch", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[6]{"3","4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Warbow", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Longbow", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Pike", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Glaive", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Dagger Pair", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Claws", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Iron-clan Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Double Bladed Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Great Nature Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Wild Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Whispering Bow", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Bloadletter", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Black Monk Stave", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Heron Spear", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Druidic Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Mistcaller", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Black Hands", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Soulscythe", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Spirithunter", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Wailing Bow", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Blight Staff", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                    new Item { Id = Guid.NewGuid().ToString(), Category = "Hunter", Text = "Leering Cane", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    new Item { Id = Guid.NewGuid().ToString(), Category = "Bags", Text = "Bag", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    new Item { Id = Guid.NewGuid().ToString(), Category = "Potions", Text = "Potion", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    new Item { Id = Guid.NewGuid().ToString(), Category = "Animals", Text = "Animal", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    new Item { Id = Guid.NewGuid().ToString(), Category = "Mounts", Text = "Mount", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},

                    new Item { Id = Guid.NewGuid().ToString(), Category = "Mounts", Text = "Mount", Icon = "https://vignette2.wikia.nocookie.net/albiononline/images/6/6a/Birch_Logs.png", Image="https://vignette2.wikia.nocookie.net/albiononline/images/5/5e/Birch-tree.png", Tiers=new string[5]{"4","5","6","7","8"}, Materials=new string[4]{"Wood", "Iron", "Cloth", "Leather" }, SpecialMaterial="", Weight="1.5", DestinyBoard="1", Production="1", Description=""},
                };

                foreach (Item item in _items)
                {
                    items.Add(item);
                }
            });
            isInitialized = true;
        }
    }
}
